import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Image
            src="https://images.unsplash.com/photo-1605460375648-278bcbd579a6"
            width={500}
            height={200}
            alt="A beautiful English Setter"
          />
        </div>
        <p>Stretched</p>

        <div style={{ width: 500, height: 200, position: "relative" }}>
          <Image
            src="https://images.unsplash.com/photo-1605460375648-278bcbd579a6"
            layout="fill"
            objectFit="cover"
            alt="A beautiful English Setter"
          />
        </div>
        <p>Cropped</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
