import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Blog Page</h1>
        <p className={styles.link}>
          <Link href="/blog/2021-01-01/happy-new-year"> New Year </Link>
        </p>
        <p className={styles.link}>
          <Link href="/blog/2021-03-05/match-update"> Match Update </Link>
        </p>
        <p className={styles.link}>
          <Link
            href={{
              pathname: "/blog/[date]/[slug]",
              query: {
                date: "2020-04-23",
                slug: "i-love-nextjs",
                foo: "bar",
              },
            }}
          >
            I Love NextJS
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
